---
- name: Configure Prometheus Alert Rules
  hosts: prometheus_servers
  tasks:
    - name: Copy alert_rules.yml to server
      copy:
        src: alert_rules.yml
        dest: /etc/prometheus/alert_rules.yml

    - name: Copy prometheus.yml to server
      copy:
        src: prometheus.yml
        dest: /etc/prometheus/prometheus.yml

    - name: Restart Prometheus service
      systemd:
        name: prometheus
        state: restarted
